export const Albums = {
    "albums": {
        "href": "https://api.spotify.com/v1/search?query=hulapalu&type=album&market=DE&offset=0&limit=10",
        "items": [
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/4rp8rIXbwp93MnStnqDGQD"
                        },
                        "href": "https://api.spotify.com/v1/artists/4rp8rIXbwp93MnStnqDGQD",
                        "id": "4rp8rIXbwp93MnStnqDGQD",
                        "name": "Andreas Gabalier",
                        "type": "artist",
                        "uri": "spotify:artist:4rp8rIXbwp93MnStnqDGQD"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AR",
                    "AT",
                    "AU",
                    "BE",
                    "BG",
                    "BO",
                    "BR",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "EC",
                    "EE",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IS",
                    "IT",
                    "JP",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MC",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "PY",
                    "RO",
                    "SE",
                    "SG",
                    "SK",
                    "SV",
                    "TH",
                    "TR",
                    "TW",
                    "US",
                    "UY",
                    "VN",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/5DzWjOZDKWIN6WwxfenOfx"
                },
                "href": "https://api.spotify.com/v1/albums/5DzWjOZDKWIN6WwxfenOfx",
                "id": "5DzWjOZDKWIN6WwxfenOfx",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/b6876a9af3bf9306a2de34df32e344078c62d5cb",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/d3c571e2443860ad279159dcaf798f4a3fedec55",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/5ac2f068c095788d2c42325a3b6717f609b71e30",
                        "width": 64
                    }
                ],
                "name": "Hulapalu",
                "release_date": "2016-01-22",
                "release_date_precision": "day",
                "type": "album",
                "uri": "spotify:album:5DzWjOZDKWIN6WwxfenOfx"
            },
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/4rp8rIXbwp93MnStnqDGQD"
                        },
                        "href": "https://api.spotify.com/v1/artists/4rp8rIXbwp93MnStnqDGQD",
                        "id": "4rp8rIXbwp93MnStnqDGQD",
                        "name": "Andreas Gabalier",
                        "type": "artist",
                        "uri": "spotify:artist:4rp8rIXbwp93MnStnqDGQD"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AR",
                    "AT",
                    "AU",
                    "BE",
                    "BG",
                    "BO",
                    "BR",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "EC",
                    "EE",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IS",
                    "IT",
                    "JP",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MC",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "PY",
                    "RO",
                    "SE",
                    "SG",
                    "SK",
                    "SV",
                    "TH",
                    "TR",
                    "TW",
                    "US",
                    "UY",
                    "VN",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/1J12MdeVUhehGusMeFlPzY"
                },
                "href": "https://api.spotify.com/v1/albums/1J12MdeVUhehGusMeFlPzY",
                "id": "1J12MdeVUhehGusMeFlPzY",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/27c57c9b9d6e2801595f72961dd04630fbfe9778",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/0ae1c25f273b29870e269a451630cde381938556",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/40c5b942274c8ad19465a196570bd98e9545d9be",
                        "width": 64
                    }
                ],
                "name": "Hulapalu (DJ Fosco Dance Mixe)",
                "release_date": "2016-03-11",
                "release_date_precision": "day",
                "type": "album",
                "uri": "spotify:album:1J12MdeVUhehGusMeFlPzY"
            },
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/4rp8rIXbwp93MnStnqDGQD"
                        },
                        "href": "https://api.spotify.com/v1/artists/4rp8rIXbwp93MnStnqDGQD",
                        "id": "4rp8rIXbwp93MnStnqDGQD",
                        "name": "Andreas Gabalier",
                        "type": "artist",
                        "uri": "spotify:artist:4rp8rIXbwp93MnStnqDGQD"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AR",
                    "AT",
                    "AU",
                    "BE",
                    "BG",
                    "BO",
                    "BR",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "EC",
                    "EE",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IS",
                    "IT",
                    "JP",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MC",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "PY",
                    "RO",
                    "SE",
                    "SG",
                    "SK",
                    "SV",
                    "TH",
                    "TR",
                    "TW",
                    "US",
                    "UY",
                    "VN",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/2v8gW4uYNxHsASenRCgTHG"
                },
                "href": "https://api.spotify.com/v1/albums/2v8gW4uYNxHsASenRCgTHG",
                "id": "2v8gW4uYNxHsASenRCgTHG",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/a997c1e3b19ea528e90b3c5e31d8e0f9dbc274d6",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/0f3380c51b54dcc933e549b7628ce80589d0a356",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/f68092cec7d2435245ec0d771463894eee0e7c0f",
                        "width": 64
                    }
                ],
                "name": "Hulapalu (One Night Song - Version)",
                "release_date": "2016-06-01",
                "release_date_precision": "day",
                "type": "album",
                "uri": "spotify:album:2v8gW4uYNxHsASenRCgTHG"
            },
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/7zwUlH72IMmTxF0DFN2WG6"
                        },
                        "href": "https://api.spotify.com/v1/artists/7zwUlH72IMmTxF0DFN2WG6",
                        "id": "7zwUlH72IMmTxF0DFN2WG6",
                        "name": "Geiles Leben",
                        "type": "artist",
                        "uri": "spotify:artist:7zwUlH72IMmTxF0DFN2WG6"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AR",
                    "AT",
                    "AU",
                    "BE",
                    "BG",
                    "BO",
                    "BR",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "EC",
                    "EE",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IS",
                    "IT",
                    "JP",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MC",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "PY",
                    "RO",
                    "SE",
                    "SG",
                    "SK",
                    "SV",
                    "TH",
                    "TR",
                    "TW",
                    "US",
                    "UY",
                    "VN",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/3wSo6xsbVx65QB0PNtlkQo"
                },
                "href": "https://api.spotify.com/v1/albums/3wSo6xsbVx65QB0PNtlkQo",
                "id": "3wSo6xsbVx65QB0PNtlkQo",
                "images": [
                    {
                        "height": 600,
                        "url": "https://i.scdn.co/image/60b0b536bebe566d20df6c313a21599f5acaa3e2",
                        "width": 600
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/52ac80c81261d7f94d59d0afed9e2b9ff05d8831",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/704a517cde18624bb83c1f1b866548edc6d60543",
                        "width": 64
                    }
                ],
                "name": "Hulapalu",
                "release_date": "2016-02-03",
                "release_date_precision": "day",
                "type": "album",
                "uri": "spotify:album:3wSo6xsbVx65QB0PNtlkQo"
            },
            {
                "album_type": "compilation",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of"
                        },
                        "href": "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
                        "id": "0LyfQWJT6nXafLPZqxe9Of",
                        "name": "Various Artists",
                        "type": "artist",
                        "uri": "spotify:artist:0LyfQWJT6nXafLPZqxe9Of"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AR",
                    "AT",
                    "AU",
                    "BE",
                    "BG",
                    "BO",
                    "BR",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "EC",
                    "EE",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IS",
                    "IT",
                    "JP",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MC",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "PY",
                    "RO",
                    "SE",
                    "SG",
                    "SK",
                    "SV",
                    "TH",
                    "TR",
                    "TW",
                    "US",
                    "UY",
                    "VN",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/1qiKhs2FsSvKEegICjZsSM"
                },
                "href": "https://api.spotify.com/v1/albums/1qiKhs2FsSvKEegICjZsSM",
                "id": "1qiKhs2FsSvKEegICjZsSM",
                "images": [
                    {
                        "height": 600,
                        "url": "https://i.scdn.co/image/b9bca6ba4b15a5d144b5ac37c54a67d8571be180",
                        "width": 600
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/2db156232d4689a4540b0caf21e55fbb3a2a7c7c",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/0912dc53eab5cd03a68cb1c89f463572143e11ca",
                        "width": 64
                    }
                ],
                "name": "Hütten Charts 2017! 80 turbostarke Hulapalu-Party-Songs für abgefahrene Après-Ski-Hits-Experten!",
                "release_date": "2016-11-25",
                "release_date_precision": "day",
                "type": "album",
                "uri": "spotify:album:1qiKhs2FsSvKEegICjZsSM"
            },
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/5y6k3t0nlR293Sbw3udhxB"
                        },
                        "href": "https://api.spotify.com/v1/artists/5y6k3t0nlR293Sbw3udhxB",
                        "id": "5y6k3t0nlR293Sbw3udhxB",
                        "name": "Die Stube Buben",
                        "type": "artist",
                        "uri": "spotify:artist:5y6k3t0nlR293Sbw3udhxB"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AR",
                    "AT",
                    "AU",
                    "BE",
                    "BG",
                    "BO",
                    "BR",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "EC",
                    "EE",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IS",
                    "IT",
                    "JP",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MC",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "PY",
                    "RO",
                    "SE",
                    "SG",
                    "SK",
                    "SV",
                    "TH",
                    "TR",
                    "TW",
                    "US",
                    "UY",
                    "VN",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/1vGZ1JCX5IBnF7aLWf64XZ"
                },
                "href": "https://api.spotify.com/v1/albums/1vGZ1JCX5IBnF7aLWf64XZ",
                "id": "1vGZ1JCX5IBnF7aLWf64XZ",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab3af0789e0878ce5a07565785caacd8937fca24",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/9ac98a8db1d75ec57e3b1b697dc9eaf63f029b80",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/f7865e01fdf5340130e92114b6c2d25afecf565f",
                        "width": 64
                    }
                ],
                "name": "Hulapalu",
                "release_date": "2017-09-22",
                "release_date_precision": "day",
                "type": "album",
                "uri": "spotify:album:1vGZ1JCX5IBnF7aLWf64XZ"
            },
            {
                "album_type": "compilation",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of"
                        },
                        "href": "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
                        "id": "0LyfQWJT6nXafLPZqxe9Of",
                        "name": "Various Artists",
                        "type": "artist",
                        "uri": "spotify:artist:0LyfQWJT6nXafLPZqxe9Of"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AR",
                    "AT",
                    "AU",
                    "BE",
                    "BG",
                    "BO",
                    "BR",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "EC",
                    "EE",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IS",
                    "IT",
                    "JP",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MC",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "PY",
                    "RO",
                    "SE",
                    "SG",
                    "SK",
                    "SV",
                    "TH",
                    "TR",
                    "TW",
                    "US",
                    "UY",
                    "VN",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/1De0VNNI1EPM0eqBdh18Nh"
                },
                "href": "https://api.spotify.com/v1/albums/1De0VNNI1EPM0eqBdh18Nh",
                "id": "1De0VNNI1EPM0eqBdh18Nh",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/5c0487c4b1c940e160529b16d8cd391d29f9c8f8",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/a0b11ea7aac5ef3b49e7dad846984118f4dc287c",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/4c187ae5d6cad6c353fde3c21e3e0e03f4ce51f0",
                        "width": 64
                    }
                ],
                "name": "Partyfieber - inkl. Hulapalu, Die immer lacht, Ham kummst, Gloana Bauer",
                "release_date": "2016-11-22",
                "release_date_precision": "day",
                "type": "album",
                "uri": "spotify:album:1De0VNNI1EPM0eqBdh18Nh"
            },
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/6nTlnlfAR0sUE3xMIYpYTT"
                        },
                        "href": "https://api.spotify.com/v1/artists/6nTlnlfAR0sUE3xMIYpYTT",
                        "id": "6nTlnlfAR0sUE3xMIYpYTT",
                        "name": "Alexander König",
                        "type": "artist",
                        "uri": "spotify:artist:6nTlnlfAR0sUE3xMIYpYTT"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AR",
                    "AT",
                    "AU",
                    "BE",
                    "BG",
                    "BO",
                    "BR",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "EC",
                    "EE",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IS",
                    "IT",
                    "JP",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MC",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "PY",
                    "RO",
                    "SE",
                    "SG",
                    "SK",
                    "SV",
                    "TH",
                    "TR",
                    "TW",
                    "US",
                    "UY",
                    "VN",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/0JlIDSNemApxCuN9rYnslC"
                },
                "href": "https://api.spotify.com/v1/albums/0JlIDSNemApxCuN9rYnslC",
                "id": "0JlIDSNemApxCuN9rYnslC",
                "images": [
                    {
                        "height": 600,
                        "url": "https://i.scdn.co/image/7913fcc23cf7ff8ace85033f6e614fc19fa8a377",
                        "width": 600
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/44e551073087555c4fb6f803290729e9dca6bfc2",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/1513d3b5023765a596107a1b7954541d0bbdce8e",
                        "width": 64
                    }
                ],
                "name": "Hulapalu",
                "release_date": "2016-03-24",
                "release_date_precision": "day",
                "type": "album",
                "uri": "spotify:album:0JlIDSNemApxCuN9rYnslC"
            },
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/3oYihDDeOdh0mmtVb0SdEc"
                        },
                        "href": "https://api.spotify.com/v1/artists/3oYihDDeOdh0mmtVb0SdEc",
                        "id": "3oYihDDeOdh0mmtVb0SdEc",
                        "name": "Die Partymacher",
                        "type": "artist",
                        "uri": "spotify:artist:3oYihDDeOdh0mmtVb0SdEc"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AR",
                    "AT",
                    "AU",
                    "BE",
                    "BG",
                    "BO",
                    "BR",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "EC",
                    "EE",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IS",
                    "IT",
                    "JP",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MC",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "PY",
                    "RO",
                    "SE",
                    "SG",
                    "SK",
                    "SV",
                    "TH",
                    "TR",
                    "TW",
                    "US",
                    "UY",
                    "VN",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/5EFPes078hSBg6hwUUCeZE"
                },
                "href": "https://api.spotify.com/v1/albums/5EFPes078hSBg6hwUUCeZE",
                "id": "5EFPes078hSBg6hwUUCeZE",
                "images": [
                    {
                        "height": 600,
                        "url": "https://i.scdn.co/image/3c9b1404a22e78f5b17ab64f071ba1caf431a918",
                        "width": 600
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/5e10c54aeec5bfccbb1d3e7bbafdaad7d6d1f49e",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/21eda0d893f1c1cc2c209e6b6ee022d54d43907e",
                        "width": 64
                    }
                ],
                "name": "Hulapalu",
                "release_date": "2018-03-28",
                "release_date_precision": "day",
                "type": "album",
                "uri": "spotify:album:5EFPes078hSBg6hwUUCeZE"
            },
            {
                "album_type": "single",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/5FSg2P9O9Qzt0hNYNrHgoD"
                        },
                        "href": "https://api.spotify.com/v1/artists/5FSg2P9O9Qzt0hNYNrHgoD",
                        "id": "5FSg2P9O9Qzt0hNYNrHgoD",
                        "name": "Alpenjodler",
                        "type": "artist",
                        "uri": "spotify:artist:5FSg2P9O9Qzt0hNYNrHgoD"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AR",
                    "AT",
                    "AU",
                    "BE",
                    "BG",
                    "BO",
                    "BR",
                    "CA",
                    "CH",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "DO",
                    "EC",
                    "EE",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GR",
                    "GT",
                    "HK",
                    "HN",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IS",
                    "IT",
                    "JP",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MC",
                    "MT",
                    "MX",
                    "MY",
                    "NI",
                    "NL",
                    "NO",
                    "NZ",
                    "PA",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "PY",
                    "RO",
                    "SE",
                    "SG",
                    "SK",
                    "SV",
                    "TH",
                    "TR",
                    "TW",
                    "US",
                    "UY",
                    "VN",
                    "ZA"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/0rb9s8V2AWkoK76Rcr4GV1"
                },
                "href": "https://api.spotify.com/v1/albums/0rb9s8V2AWkoK76Rcr4GV1",
                "id": "0rb9s8V2AWkoK76Rcr4GV1",
                "images": [
                    {
                        "height": 600,
                        "url": "https://i.scdn.co/image/f0b4be066ef9f93027b246c1123c94c60869fa48",
                        "width": 600
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/cc3327f8ba2400908daee390b3941cd77955deb5",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/8ed7d6455234f06bd7ba8fdf822607069722786b",
                        "width": 64
                    }
                ],
                "name": "Hulapalu",
                "release_date": "2016-04-19",
                "release_date_precision": "day",
                "type": "album",
                "uri": "spotify:album:0rb9s8V2AWkoK76Rcr4GV1"
            }
        ],
        "limit": 10,
        "next": "https://api.spotify.com/v1/search?query=hulapalu&type=album&market=DE&offset=10&limit=10",
        "offset": 0,
        "previous": null,
        "total": 26
    }
}