export const albumTracks = {
    "href": "https://api.spotify.com/v1/albums/5DzWjOZDKWIN6WwxfenOfx/tracks?offset=0&limit=10",
    "items": [
        {
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/4rp8rIXbwp93MnStnqDGQD"
                    },
                    "href": "https://api.spotify.com/v1/artists/4rp8rIXbwp93MnStnqDGQD",
                    "id": "4rp8rIXbwp93MnStnqDGQD",
                    "name": "Andreas Gabalier",
                    "type": "artist",
                    "uri": "spotify:artist:4rp8rIXbwp93MnStnqDGQD"
                }
            ],
            "available_markets": [
                "AD",
                "AR",
                "AT",
                "AU",
                "BE",
                "BG",
                "BO",
                "BR",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "EC",
                "EE",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HU",
                "ID",
                "IE",
                "IL",
                "IS",
                "IT",
                "JP",
                "LI",
                "LT",
                "LU",
                "LV",
                "MC",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "PA",
                "PE",
                "PH",
                "PL",
                "PT",
                "PY",
                "RO",
                "SE",
                "SG",
                "SK",
                "SV",
                "TH",
                "TR",
                "TW",
                "US",
                "UY",
                "VN",
                "ZA"
            ],
            "disc_number": 1,
            "duration_ms": 180253,
            "explicit": false,
            "external_urls": {
                "spotify": "https://open.spotify.com/track/7M9Om994fy8bElE7COV9OG"
            },
            "href": "https://api.spotify.com/v1/tracks/7M9Om994fy8bElE7COV9OG",
            "id": "7M9Om994fy8bElE7COV9OG",
            "is_local": false,
            "name": "Hulapalu",
            "preview_url": "https://p.scdn.co/mp3-preview/6464c79dfed46e81f02d0b1237091e4b28d2047f?cid=774b29d4f13844c495f206cafdad9c86",
            "track_number": 1,
            "type": "track",
            "uri": "spotify:track:7M9Om994fy8bElE7COV9OG"
        },
        {
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/4rp8rIXbwp93MnStnqDGQD"
                    },
                    "href": "https://api.spotify.com/v1/artists/4rp8rIXbwp93MnStnqDGQD",
                    "id": "4rp8rIXbwp93MnStnqDGQD",
                    "name": "Andreas Gabalier",
                    "type": "artist",
                    "uri": "spotify:artist:4rp8rIXbwp93MnStnqDGQD"
                }
            ],
            "available_markets": [
                "AD",
                "AR",
                "AT",
                "AU",
                "BE",
                "BG",
                "BO",
                "BR",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "EC",
                "EE",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HU",
                "ID",
                "IE",
                "IL",
                "IS",
                "IT",
                "JP",
                "LI",
                "LT",
                "LU",
                "LV",
                "MC",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "PA",
                "PE",
                "PH",
                "PL",
                "PT",
                "PY",
                "RO",
                "SE",
                "SG",
                "SK",
                "SV",
                "TH",
                "TR",
                "TW",
                "US",
                "UY",
                "VN",
                "ZA"
            ],
            "disc_number": 1,
            "duration_ms": 220936,
            "explicit": false,
            "external_urls": {
                "spotify": "https://open.spotify.com/track/5FEqwTN3JgS3bSCsQtYtRX"
            },
            "href": "https://api.spotify.com/v1/tracks/5FEqwTN3JgS3bSCsQtYtRX",
            "id": "5FEqwTN3JgS3bSCsQtYtRX",
            "is_local": false,
            "name": "Hulapalu - Harris & Ford Radio Edit",
            "preview_url": "https://p.scdn.co/mp3-preview/e435ccdfb5261834cc416f6b831eac18a466e82a?cid=774b29d4f13844c495f206cafdad9c86",
            "track_number": 2,
            "type": "track",
            "uri": "spotify:track:5FEqwTN3JgS3bSCsQtYtRX"
        },
        {
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/4rp8rIXbwp93MnStnqDGQD"
                    },
                    "href": "https://api.spotify.com/v1/artists/4rp8rIXbwp93MnStnqDGQD",
                    "id": "4rp8rIXbwp93MnStnqDGQD",
                    "name": "Andreas Gabalier",
                    "type": "artist",
                    "uri": "spotify:artist:4rp8rIXbwp93MnStnqDGQD"
                }
            ],
            "available_markets": [
                "AD",
                "AR",
                "AT",
                "AU",
                "BE",
                "BG",
                "BO",
                "BR",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "EC",
                "EE",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HU",
                "ID",
                "IE",
                "IL",
                "IS",
                "IT",
                "JP",
                "LI",
                "LT",
                "LU",
                "LV",
                "MC",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "PA",
                "PE",
                "PH",
                "PL",
                "PT",
                "PY",
                "RO",
                "SE",
                "SG",
                "SK",
                "SV",
                "TH",
                "TR",
                "TW",
                "US",
                "UY",
                "VN",
                "ZA"
            ],
            "disc_number": 1,
            "duration_ms": 280923,
            "explicit": false,
            "external_urls": {
                "spotify": "https://open.spotify.com/track/2YTSkSqglSgpQNJxknCUQ0"
            },
            "href": "https://api.spotify.com/v1/tracks/2YTSkSqglSgpQNJxknCUQ0",
            "id": "2YTSkSqglSgpQNJxknCUQ0",
            "is_local": false,
            "name": "Hulapalu - Harris & Ford Extended Mix",
            "preview_url": "https://p.scdn.co/mp3-preview/53f6b207cc61e31fe16ebf5935d256f56d471bfd?cid=774b29d4f13844c495f206cafdad9c86",
            "track_number": 3,
            "type": "track",
            "uri": "spotify:track:2YTSkSqglSgpQNJxknCUQ0"
        },
        {
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/4rp8rIXbwp93MnStnqDGQD"
                    },
                    "href": "https://api.spotify.com/v1/artists/4rp8rIXbwp93MnStnqDGQD",
                    "id": "4rp8rIXbwp93MnStnqDGQD",
                    "name": "Andreas Gabalier",
                    "type": "artist",
                    "uri": "spotify:artist:4rp8rIXbwp93MnStnqDGQD"
                }
            ],
            "available_markets": [
                "AD",
                "AR",
                "AT",
                "AU",
                "BE",
                "BG",
                "BO",
                "BR",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "EC",
                "EE",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HU",
                "ID",
                "IE",
                "IL",
                "IS",
                "IT",
                "JP",
                "LI",
                "LT",
                "LU",
                "LV",
                "MC",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "PA",
                "PE",
                "PH",
                "PL",
                "PT",
                "PY",
                "RO",
                "SE",
                "SG",
                "SK",
                "SV",
                "TH",
                "TR",
                "TW",
                "US",
                "UY",
                "VN",
                "ZA"
            ],
            "disc_number": 1,
            "duration_ms": 315706,
            "explicit": false,
            "external_urls": {
                "spotify": "https://open.spotify.com/track/1HQxTc7EOf9nut1on8GxsY"
            },
            "href": "https://api.spotify.com/v1/tracks/1HQxTc7EOf9nut1on8GxsY",
            "id": "1HQxTc7EOf9nut1on8GxsY",
            "is_local": false,
            "name": "Hulapalu - Live",
            "preview_url": "https://p.scdn.co/mp3-preview/2989e0eae347e81ab15073c4aa367e28c8944d2d?cid=774b29d4f13844c495f206cafdad9c86",
            "track_number": 4,
            "type": "track",
            "uri": "spotify:track:1HQxTc7EOf9nut1on8GxsY"
        }
    ],
    "limit": 10,
    "next": null,
    "offset": 0,
    "previous": null,
    "total": 4
}